name: Publish NuGet Package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build projects
      run: dotnet build --configuration Release

    - name: Install tree
      run: sudo apt-get install -y tree

    - name: List directory structure
      run: tree -d

    - name: Show working directory
      run: pwd

    - name: List contents of build output directory (TestLogger)
      run: ls -R ./src/AzurePipelines.TestLogger/bin/Release/net8.0

    - name: List contents of build output directory (CompleteTestRun)
      run: ls -R ./src/CompleteTestRun/bin/Release/net8.0

    - name: List contents of build output directory (CreateTestRun)
      run: ls -R ./src/CreateTestRun/bin/Release/net8.0

    - name: Pack NuGet package
      run: nuget pack .nuspec -OutputDirectory ./nupkg

    - name: Publish NuGet package
      run: dotnet nuget push --source "TestAutomation" --api-key az https://pkgs.dev.azure.com/wtw-bda-outsourcing-product/BenefitConnect/_packaging/TestAutomation/nuget/v3/index.json